<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>5936d6d9-d3fb-4cfc-bfa7-e3eaa3050ee3</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../ApplicationManagerAPI/ApplicationManagerAPI.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    </ItemGroup>

</Project>
